package org.arpha.dto.audit;

public enum Action {
    CREATE_USER, FIND_USER_BY_ID, FIND_USER_BY_EMAIL, UPDATE_USER, DELETE_USER_BY_ID, ACTIVATE_ACCOUNT, UPLOAD_FILE,
    DELETE_FILE_BY_ID, FIND_FILE_BY_ID;
}
