spring:
  profiles:
    active: default
  application:
    name: tabletop-games-shop
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9999

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

azure:
  services:
    communication:
      connectionString: ${AZURE_COMMUNICATION_CONNECTION_STRING}
      senderEmail: ${AZURE_COMMUNICATION_EMAIL}
      senderPhoneNumber: ${AZURE_COMMUNICATION_PHONE}
    storage:
      connectionString: ${BLOB_URL}
      containerName: ${BLOB_CONTAINER_NAME}
