spring:
  profiles:
    active: default
  application:
    name: tabletop-games-shop
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
server:
  port: 9999
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

releans:
  apiKey: ${SMS_SERVICE_API_KEY}
  senderName: ${SMS_SERVICE_SENDER}

azure:
  services:
    communication:
      connectionString: ${AZURE_COMMUNICATION_CONNECTION_STRING}
      senderEmail: ${AZURE_COMMUNICATION_EMAIL}
    storage:
      connectionString: ${AZURE_BLOB_CONNECTION_STRING}
      containerName: ${AZURE_BLOB_CONTAINER_NAME}
      linkExpiration: ${AZURE_BLOB_LINK_EXPIRATION}
