spring:
  profiles:
    active: default
  application:
    name: tabletop-games-shop
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    cors:
      allowedOrigins: ${CORS_ALLOWED_ORIGINS}
    token:
      secret: ${JWT_SECRET}
      expiration:
        accessToken: ${ACCESS_TOKEN_EXPIRATION}
        refreshToken: ${REFRESH_TOKEN_EXPIRATION}
    oauth2:
      feRedirectUrl: ${FE_URL}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
server:
  port: ${PORT:9999}

azure:
  services:
    communication:
      connectionString: ${AZURE_COMMUNICATION_CONNECTION_STRING}
      senderEmail: ${AZURE_COMMUNICATION_EMAIL}
    storage:
      connectionString: ${AZURE_BLOB_CONNECTION_STRING}
      containerName: ${AZURE_BLOB_CONTAINER_NAME}
      linkExpiration: ${AZURE_BLOB_LINK_EXPIRATION}
nova-poshta:
  config:
    apiKey: ${NOVA_POSHTA_API_KEY}
    apiUrl: https://api.novaposhta.ua/v2.0/json/
kyivstar:
  baseUrl: ${KYIVSTAR_BASE_URL:https://api-gateway.kyivstar.ua}
  #Should be specified in hours
  tokenExpiration: ${KYIVSTAR_AUTH_TOKEN_EXPIRY:7}
  clientId: ${KYIVSTAR_CLIENT_ID}
  clientSecret: ${KYIVSTAR_CLIENT_SECRET}
  environment: ${KYIVSTAR_ENVIRONMENT:/sandbox}
  apiVersion: ${KYIVSTAR_API_VERSION:v1beta}
  senderName: ${KYIVSTAR_SENDER_NAME:messagedesk}
