package org.arpha.dto.order.enums;

public enum OrderStatus {
    NEW, CANCELLED, ON_THE_WAY, WAITING_TAKEOUT, CREATED_CONSIGNMENT, CONSIGNMENT_NOT_FOUND,
    IN_CITY_INTERREGIONAL, IN_CITY_LOCAL, HEADING_TO_CITY, IN_CITY_ESTIMATED_DELIVERY, ARRIVED_AT_WAREHOUSE,
    ARRIVED_AT_LOCKER, RECEIVED, RECEIVED_PENDING_PAYMENT, RECEIVED_PAYMENT_ISSUED, PROCESSING, REFUSED_RETURN_ORDERED,
    REFUSED, ADDRESS_CHANGED, STORAGE_ENDED, REVERSE_DELIVERY_CREATED, FAILED_DELIVERY_NO_CONTACT, DELIVERY_DATE_CHANGED
}
